backend:
  name: git-gateway
  repo: solazio/adrianpenu.com
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

# Use local_backend to run the cms locally - run the server with npx netlify-cms-proxy-server
# local_backend: true

media_folder: static/img
public_folder: /img

site_url: https://adrianpenu.com

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          default: false,
        }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "paintings"
    label: "Paintings"
    folder: "src/pages/work"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "category-page",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Position",
          name: "position",
          widget: "number",
          valueType: "int",
          step: 1,
        }
      - {
          name: "images",
          label: "Images",
          widget: "list",
          fields:
            [
              { label: "Title", name: "title", widget: "string" },
              { label: "Alt", name: "alt", widget: "string" },
              { label: "Slug", name: "slug", widget: "string" },
              {
                label: "Featured",
                name: "featured",
                widget: "boolean",
                default: false,
              },
              { label: "Type", name: "type", widget: "string" },
              { label: "Dimensions", name: "dimensions", widget: "string" },
              { label: "Price", name: "price", widget: "string" },
              { label: "Shipping", name: "shipping", widget: "string" },
              {
                label: "Position",
                name: "position",
                widget: "number",
                valueType: "int",
                step: 1,
              },
              { label: "Image", name: "image", widget: "image" },
            ],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "image", widget: "image" }
          - { label: "Body", name: "body", widget: "markdown" }
